#!/bin/bash

# This script manages Nginx Maintenance Mode
# Usage: maintenance (on|off|sleep NUM VALUE)
# Example:
# - maintenance on: Switches on Maintenance Mode
# - maintenance off: Switches off Maintenance Mode
# - maintenance sleep: Switches on Maintenance Mode temporarily for 15 minutes
# - maintenance sleep 10 min: Switches on Maintenance Mode temporarily for 10 minutes
# Valid VALUE options: seconds (sec, secs), minutes (min, mins), hours (hour, hr), days (day)

if [ -z $1 ]; then
    # Display usage instructions if no argument is passed
    echo "Usage: maintenance (on|off|sleep NUM VALUE)"
    echo ""
    echo "Example: "
    echo ""
    echo "maintenance on - Switches on Maintenance Mode"
    echo "maintenance off - Switches off Maintenance Mode"
    echo "maintenance sleep - Switches on Maintenance Mode temporarily for 15 minutes"
    echo "maintenance sleep 10 min - Switches on Maintenance Mode temporarily for 10 min"
    echo ""
    echo "Valid VALUE is seconds (sec, secs), minutes (min, mins) , hours (hour, hr) , days (day)"
    exit
fi

case "${1,,}" in
    "on" | "true" )
        # Activate maintenance mode
        sed -i "s|include /etc/nginx/sites.enabled/\*.conf;|#include /etc/nginx/sites.enabled/\*.conf;|g" /etc/nginx/nginx.conf
        sed -i "s|#include /etc/nginx/templates/maintenance.template;|include /etc/nginx/templates/maintenance.template;|g" /etc/nginx/nginx.conf
        nginx -s reload
        echo 'Maintenance Mode Activated'
    ;;
    "off" | "false" )
        # Deactivate maintenance mode
        sed -i "s|#include /etc/nginx/sites.enabled/\*.conf;|include /etc/nginx/sites.enabled/\*.conf;|g" /etc/nginx/nginx.conf
        sed -i "s|include /etc/nginx/templates/maintenance.template;|#include /etc/nginx/templates/maintenance.template;|g" /etc/nginx/nginx.conf
        nginx -s reload
        echo 'Maintenance Mode Deactivated'
    ;;
    "sleep" | "temp" )
        # Temporarily activate maintenance mode
        sed -i "s|include /etc/nginx/sites.enabled/\*.conf;|#include /etc/nginx/sites.enabled/\*.conf;|g" /etc/nginx/nginx.conf
        sed -i "s|#include /etc/nginx/templates/maintenance.template;|include /etc/nginx/templates/maintenance.template;|g" /etc/nginx/nginx.conf
        nginx -s reload

        # Set default sleep duration if not provided
        if [ -z $2 ]; then
            sleepnum="15"
            sleepcalc=$((15 * 60))
        fi

        # Set default time unit if not provided
        if [ -z $3 ]; then
            set -- "${@:1:2}" "min"
        fi

        # Calculate sleep duration based on unit
        case "${3,,}" in
            "min" | "minutes" )
                sleepcalc=$(($2 * 60))
                sleepdesc="minutes"
            ;;
            "seconds" | "secs" | "sec" )
                sleepcalc=$(($2 * 1))
                sleepdesc="seconds"
            ;;
            "hour" | "hours" | "hr" | "hrs" )
                sleepcalc=$(($2 * 3600))
                sleepdesc="hour(s)"
            ;;
            "day" | "days" )
                sleepcalc=$(($2 * 86400))
                sleepdesc="day(s)"
            ;;
        esac

        echo "Maintenance Mode Temporarily Activated for $sleepnum $sleepdesc"
        sleep $sleepcalc

        # Deactivate maintenance mode after sleep duration
        sed -i "s|#include /etc/nginx/sites.enabled/\*.conf;|include /etc/nginx/sites.enabled/\*.conf;|g" /etc/nginx/nginx.conf
        sed -i "s|include /etc/nginx/templates/maintenance.template;|#include /etc/nginx/templates/maintenance.template;|g" /etc/nginx/nginx.conf
        nginx -s reload
        echo 'Maintenance Mode Deactivated'
    ;;
    * )
        # Handle invalid input
        echo "Invalid option. Please use 'on', 'off', or 'sleep NUM VALUE'."
        exit 1
    ;;
esac
