#!/command/with-contenv bash

# Source common container functions
source /assets/functions/00-container

# Prepare service dependencies
prepare_service 10-nginx
PROCESS_NAME="nginx-config-reload"

# Check if auto-reload on configuration change is enabled
if var_true "${NGINX_RELOAD_ON_CONFIG_CHANGE}" ; then
    # Notify the user that auto-reload functionality is enabled
    print_notice "Enabling Auto Reload of Nginx Configuration when configuration files change"
else
    # Stop the nginx-config-reload service if auto-reload is disabled
    service_stop 11-nginx-config-reload
fi

# Start the service and release control
liftoff
