#!/command/with-contenv bash

# Load common container functions
source /assets/functions/00-container

# Define the process name for logging and monitoring
PROCESS_NAME="nginx"

# Check if the container is properly initialized
check_container_initialized

# Ensure that the service has been initialized
check_service_initialized init

# Prepare the service to start
liftoff

# Log the Nginx startup message
print_start "Starting nginx ${NGINX_VERSION}"

# Execute the Nginx process
exec nginx
